"""
Entry point for pcse_gym package. Handles imports and Gym Environment
registration.

Written by Will Solow, 2024
"""

from gymnasium.envs.registration import register

# Default Annual Environments
register(
    id="lnpkw-v0",
    entry_point="pcse_gym.envs.wofost_annual:Limited_NPKW_Env",
)
register(
    id="pp-v0",
    entry_point="pcse_gym.envs.wofost_annual:PP_Env",
)
register(
    id="lnpk-v0",
    entry_point="pcse_gym.envs.wofost_annual:Limited_NPK_Env",
)
register(
    id="ln-v0",
    entry_point="pcse_gym.envs.wofost_annual:Limited_N_Env",
)
register(
    id="lnw-v0",
    entry_point="pcse_gym.envs.wofost_annual:Limited_NW_Env",
)
register(
    id="lw-v0",
    entry_point="pcse_gym.envs.wofost_annual:Limited_W_Env",
)

# Single year planting Environments
register(
    id="plant-lnpkw-v0",
    entry_point="pcse_gym.envs.plant_annual:Plant_Limited_NPKW_Env",
)
register(
    id="plant-pp-v0",
    entry_point="pcse_gym.envs.plant_annual:Plant_PP_Env",
)
register(
    id="plant-lnpk-v0",
    entry_point="pcse_gym.envs.plant_annual:Plant_Limited_NPK_Env",
)
register(
    id="plant-ln-v0",
    entry_point="pcse_gym.envs.plant_annual:Plant_Limited_N_Env",
)
register(
    id="plant-lnw-v0",
    entry_point="pcse_gym.envs.plant_annual:Plant_Limited_NW_Env",
)
register(
    id="plant-lw-v0",
    entry_point="pcse_gym.envs.plant_annual:Plant_Limited_W_Env",
)

# Single year harvesting environments
register(
    id="harvest-lnpkw-v0",
    entry_point="pcse_gym.envs.harvest_annual:Harvest_Limited_NPKW_Env",
)
register(
    id="harvest-pp-v0",
    entry_point="pcse_gym.envs.harvest_annual:Harvest_PP_Env",
)
register(
    id="harvest-lnpk-v0",
    entry_point="pcse_gym.envs.harvest_annual:Harvest_Limited_NPK_Env",
)
register(
    id="harvest-ln-v0",
    entry_point="pcse_gym.envs.harvest_annual:Harvest_Limited_N_Env",
)
register(
    id="harvest-lnw-v0",
    entry_point="pcse_gym.envs.harvest_annual:Harvest_Limited_NW_Env",
)
register(
    id="harvest-lw-v0",
    entry_point="pcse_gym.envs.harvest_annual:Harvest_Limited_W_Env",
)

# Default perennial environments
register(
    id="perennial-lnpkw-v0",
    entry_point="pcse_gym.envs.wofost_perennial:Perennial_Limited_NPKW_Env",
)
register(
    id="perennial-pp-v0",
    entry_point="pcse_gym.envs.wofost_perennial:Perennial_PP_Env",
)
register(
    id="perennial-lnpk-v0",
    entry_point="pcse_gym.envs.wofost_perennial:Perennial_Limited_NPK_Env",
)
register(
    id="perennial-ln-v0",
    entry_point="pcse_gym.envs.wofost_perennial:Perennial_Limited_N_Env",
)
register(
    id="perennial-lnw-v0",
    entry_point="pcse_gym.envs.wofost_perennial:Perennial_Limited_NW_Env",
)
register(
    id="perennial-lw-v0",
    entry_point="pcse_gym.envs.wofost_perennial:Perennial_Limited_W_Env",
)

# Perennial planting Environments
register(
    id="perennial-plant-lnpkw-v0",
    entry_point="pcse_gym.envs.plant_perennial:Perennial_Plant_Limited_NPKW_Env",
)
register(
    id="perennial-plant-pp-v0",
    entry_point="pcse_gym.envs.plant_perennial:Perennial_Plant_PP_Env",
)
register(
    id="perennial-plant-lnpk-v0",
    entry_point="pcse_gym.envs.plant_perennial:Perennial_Plant_Limited_NPK_Env",
)
register(
    id="perennial-plant-ln-v0",
    entry_point="pcse_gym.envs.plant_perennial:Perennial_Plant_Limited_N_Env",
)
register(
    id="perennial-plant-lnw-v0",
    entry_point="pcse_gym.envs.plant_perennial:Perennial_Plant_Limited_NW_Env",
)
register(
    id="perennial-plant-lw-v0",
    entry_point="pcse_gym.envs.plant_perennial:Perennial_Plant_Limited_W_Env",
)

# Perennial harvest environemnts
register(
    id="perennial-harvest-lnpkw-v0",
    entry_point="pcse_gym.envs.harvest_perennial:Perennial_Harvest_Limited_NPKW_Env",
)
register(
    id="perennial-harvest-pp-v0",
    entry_point="pcse_gym.envs.harvest_perennial:Perennial_Harvest_PP_Env",
)
register(
    id="perennial-harvest-lnpk-v0",
    entry_point="pcse_gym.envs.harvest_perennial:Perennial_Harvest_Limited_NPK_Env",
)
register(
    id="perennial-harvest-ln-v0",
    entry_point="pcse_gym.envs.harvest_perennial:Perennial_Harvest_Limited_N_Env",
)
register(
    id="perennial-harvest-lnw-v0",
    entry_point="pcse_gym.envs.harvest_perennial:Perennial_Harvest_Limited_NW_Env",
)
register(
    id="perennial-harvest-lw-v0",
    entry_point="pcse_gym.envs.harvest_perennial:Perennial_Harvest_Limited_W_Env",
)

# Default Grape environments
register(
    id="grape-lnpkw-v0",
    entry_point="pcse_gym.envs.wofost_grape:Grape_Limited_NPKW_Env",
)
register(
    id="grape-pp-v0",
    entry_point="pcse_gym.envs.wofost_grape:Grape_PP_Env",
)
register(
    id="grape-lnpk-v0",
    entry_point="pcse_gym.envs.wofost_grape:Grape_Limited_NPK_Env",
)
register(
    id="grape-ln-v0",
    entry_point="pcse_gym.envs.wofost_grape:Grape_Limited_N_Env",
)
register(
    id="grape-lnw-v0",
    entry_point="pcse_gym.envs.wofost_grape:Grape_Limited_NW_Env",
)
register(
    id="grape-lw-v0",
    entry_point="pcse_gym.envs.wofost_grape:Grape_Limited_W_Env",
)

# Default Multi Annual Environments
register(
    id="multi-lnpkw-v0",
    entry_point="pcse_gym.envs.multi_annual:Multi_Limited_NPKW_Env",
)
register(
    id="multi-pp-v0",
    entry_point="pcse_gym.envs.multi_annual:Multi_PP_Env",
)
register(
    id="multi-lnpk-v0",
    entry_point="pcse_gym.envs.multi_annual:Multi_Limited_NPK_Env",
)
register(
    id="multi-ln-v0",
    entry_point="pcse_gym.envs.multi_annual:Multi_Limited_N_Env",
)
register(
    id="multi-lnw-v0",
    entry_point="pcse_gym.envs.multi_annual:Multi_Limited_NW_Env",
)
register(
    id="multi-lw-v0",
    entry_point="pcse_gym.envs.multi_annual:Multi_Limited_W_Env",
)

# Default Multi Annual Environments
register(
    id="multi-perennial-lnpkw-v0",
    entry_point="pcse_gym.envs.multi_perennial:Perennial_Multi_Limited_NPKW_Env",
)
register(
    id="multi-perennial-pp-v0",
    entry_point="pcse_gym.envs.multi_perennial:Perennial_Multi_PP_Env",
)
register(
    id="multi-perennial-lnpk-v0",
    entry_point="pcse_gym.envs.multi_perennial:Perennial_Multi_Limited_NPK_Env",
)
register(
    id="multi-perennial-ln-v0",
    entry_point="pcse_gym.envs.multi_perennial:Perennial_Multi_Limited_N_Env",
)
register(
    id="multi-perennial-lnw-v0",
    entry_point="pcse_gym.envs.multi_perennial:Perennial_Multi_Limited_NW_Env",
)
register(
    id="multi-perennial-lw-v0",
    entry_point="pcse_gym.envs.multi_perennial:Perennial_Multi_Limited_W_Env",
)

# Layered Default Annual Environments
register(
    id="llnpkw-v0",
    entry_point="pcse_gym.envs.wofost_annual:Limited_Layered_NPKW_Env",
)
register(
    id="lpp-v0",
    entry_point="pcse_gym.envs.wofost_annual:Layered_PP_Env",
)
register(
    id="llnpk-v0",
    entry_point="pcse_gym.envs.wofost_annual:Limited_Layered_NPK_Env",
)
register(
    id="lln-v0",
    entry_point="pcse_gym.envs.wofost_annual:Limited_Layered_N_Env",
)
register(
    id="llnw-v0",
    entry_point="pcse_gym.envs.wofost_annual:Limited_Layered_NW_Env",
)
register(
    id="llw-v0",
    entry_point="pcse_gym.envs.wofost_annual:Limited_Layered_W_Env",
)

# Layered Single year planting Environments
register(
    id="plant-llnpkw-v0",
    entry_point="pcse_gym.envs.plant_annual:Plant_Limited_Layered_NPKW_Env",
)
register(
    id="plant-lpp-v0",
    entry_point="pcse_gym.envs.plant_annual:Plant_Layered_PP_Env",
)
register(
    id="plant-llnpk-v0",
    entry_point="pcse_gym.envs.plant_annual:Plant_Limited_Layered_NPK_Env",
)
register(
    id="plant-lln-v0",
    entry_point="pcse_gym.envs.plant_annual:Plant_Limited_Layered_N_Env",
)
register(
    id="plant-llnw-v0",
    entry_point="pcse_gym.envs.plant_annual:Plant_Limited_Layered_NW_Env",
)
register(
    id="plant-llw-v0",
    entry_point="pcse_gym.envs.plant_annual:Plant_Limited_Layered_W_Env",
)

# Layered Single year harvesting environments
register(
    id="harvest-llnpkw-v0",
    entry_point="pcse_gym.envs.harvest_annual:Harvest_Limited_Layered_NPKW_Env",
)
register(
    id="harvest-lpp-v0",
    entry_point="pcse_gym.envs.harvest_annual:Harvest_Layered_PP_Env",
)
register(
    id="harvest-llnpk-v0",
    entry_point="pcse_gym.envs.harvest_annual:Harvest_Limited_Layered_NPK_Env",
)
register(
    id="harvest-lln-v0",
    entry_point="pcse_gym.envs.harvest_annual:Harvest_Limited_Layered_N_Env",
)
register(
    id="harvest-llnw-v0",
    entry_point="pcse_gym.envs.harvest_annual:Harvest_Limited_Layered_NW_Env",
)
register(
    id="harvest-llw-v0",
    entry_point="pcse_gym.envs.harvest_annual:Harvest_Limited_Layered_W_Env",
)

# Layered Default perennial environments
register(
    id="perennial-llnpkw-v0",
    entry_point="pcse_gym.envs.wofost_perennial:Perennial_Limited_Layered_NPKW_Env",
)
register(
    id="perennial-lpp-v0",
    entry_point="pcse_gym.envs.wofost_perennial:Perennial_Layered_PP_Env",
)
register(
    id="perennial-llnpk-v0",
    entry_point="pcse_gym.envs.wofost_perennial:Perennial_Limited_Layered_NPK_Env",
)
register(
    id="perennial-lln-v0",
    entry_point="pcse_gym.envs.wofost_perennial:Perennial_Limited_Layered_N_Env",
)
register(
    id="perennial-llnw-v0",
    entry_point="pcse_gym.envs.wofost_perennial:Perennial_Limited_Layered_NW_Env",
)
register(
    id="perennial-llw-v0",
    entry_point="pcse_gym.envs.wofost_perennial:Perennial_Limited_Layered_W_Env",
)

# Layered Perennial planting Environments
register(
    id="perennial-plant-llnpkw-v0",
    entry_point="pcse_gym.envs.plant_perennial:Perennial_Plant_Limited_Layered_NPKW_Env",
)
register(
    id="perennial-plant-lpp-v0",
    entry_point="pcse_gym.envs.plant_perennial:Perennial_Plant_Layered_PP_Env",
)
register(
    id="perennial-plant-llnpk-v0",
    entry_point="pcse_gym.envs.plant_perennial:Perennial_Plant_Limited_Layered_NPK_Env",
)
register(
    id="perennial-plant-lln-v0",
    entry_point="pcse_gym.envs.plant_perennial:Perennial_Plant_Limited_Layered_N_Env",
)
register(
    id="perennial-plant-llnw-v0",
    entry_point="pcse_gym.envs.plant_perennial:Perennial_Plant_Limited_Layered_NW_Env",
)
register(
    id="perennial-plant-llw-v0",
    entry_point="pcse_gym.envs.plant_perennial:Perennial_Plant_Limited_Layered_W_Env",
)

# Layered Perennial harvest environemnts
register(
    id="perennial-harvest-llnpkw-v0",
    entry_point="pcse_gym.envs.harvest_perennial:Perennial_Harvest_Limited_Layered_NPKW_Env",
)
register(
    id="perennial-harvest-lpp-v0",
    entry_point="pcse_gym.envs.harvest_perennial:Perennial_Harvest_Layered_PP_Env",
)
register(
    id="perennial-harvest-llnpk-v0",
    entry_point="pcse_gym.envs.harvest_perennial:Perennial_Harvest_Limited_Layered_NPK_Env",
)
register(
    id="perennial-harvest-lln-v0",
    entry_point="pcse_gym.envs.harvest_perennial:Perennial_Harvest_Limited_Layered_N_Env",
)
register(
    id="perennial-harvest-llnw-v0",
    entry_point="pcse_gym.envs.harvest_perennial:Perennial_Harvest_Limited_Layered_NW_Env",
)
register(
    id="perennial-harvest-llw-v0",
    entry_point="pcse_gym.envs.harvest_perennial:Perennial_Harvest_Limited_Layered_W_Env",
)

# Layered Default Grape environments
register(
    id="grape-llnpkw-v0",
    entry_point="pcse_gym.envs.wofost_grape:Grape_Limited_Layered_NPKW_Env",
)
register(
    id="grape-lpp-v0",
    entry_point="pcse_gym.envs.wofost_grape:Grape_Layered_PP_Env",
)
register(
    id="grape-llnpk-v0",
    entry_point="pcse_gym.envs.wofost_grape:Grape_Limited_Layered_NPK_Env",
)
register(
    id="grape-lln-v0",
    entry_point="pcse_gym.envs.wofost_grape:Grape_Limited_Layered_N_Env",
)
register(
    id="grape-llnw-v0",
    entry_point="pcse_gym.envs.wofost_grape:Grape_Limited_Layered_NW_Env",
)
register(
    id="grape-llw-v0",
    entry_point="pcse_gym.envs.wofost_grape:Grape_Limited_Layered_W_Env",
)

# Layered Default Annual Environments
register(
    id="multi-llnpkw-v0",
    entry_point="pcse_gym.envs.multi_annual:Multi_Limited_Layered_NPKW_Env",
)
register(
    id="multi-lpp-v0",
    entry_point="pcse_gym.envs.multi_annual:Multi_Layered_PP_Env",
)
register(
    id="multi-llnpk-v0",
    entry_point="pcse_gym.envs.multi_annual:Multi_Limited_Layered_NPK_Env",
)
register(
    id="multi-lln-v0",
    entry_point="pcse_gym.envs.multi_annual:Multi_Limited_Layered_N_Env",
)
register(
    id="multi-llnw-v0",
    entry_point="pcse_gym.envs.multi_annual:Multi_Limited_Layered_NW_Env",
)
register(
    id="multi-llw-v0",
    entry_point="pcse_gym.envs.multi_annual:Multi_Limited_Layered_W_Env",
)

# Layered Default Perennial Environments
register(
    id="multi-perennial-llnpkw-v0",
    entry_point="pcse_gym.envs.multi_perennial:Perennial_Multi_Limited_Layered_NPKW_Env",
)
register(
    id="multi-perennial-lpp-v0",
    entry_point="pcse_gym.envs.multi_perennial:Perennial_Multi_Layered_PP_Env",
)
register(
    id="multi-perennial-llnpk-v0",
    entry_point="pcse_gym.envs.multi_perennial:Perennial_Multi_Limited_Layered_NPK_Env",
)
register(
    id="multi-perennial-lln-v0",
    entry_point="pcse_gym.envs.multi_perennial:Perennial_Multi_Limited_Layered_N_Env",
)
register(
    id="multi-perennial-llnw-v0",
    entry_point="pcse_gym.envs.multi_perennial:Perennial_Multi_Limited_Layered_NW_Env",
)
register(
    id="multi-perennial-llw-v0",
    entry_point="pcse_gym.envs.multi_perennial:Perennial_Multi_Limited_Layered_W_Env",
)
